### ISSUE TITLE
Tests are failing because of invalid cache-restore on GitHub Actions

### ISSUE THREAD

**Issue by simonwiles** [sul-cidr/sati#4]
```yaml
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
```
This results in the the latest patch release for 3.8 being used (`3.8.x`) as seems reasonable.  However, if a cached `.venv` created with a different patch version is restored, the build fails (not sure if this might be considered a `pipenv` bug?).

In any event, two options present themselves:

1) Pin the patch version of Python (for the Actions runner, if not necessarily for the project as a whole).
2) Tag the cache with the `major.minor.patch` version of python it was built with, and invalidate as appropriate.
